title = "Electrify Canberra"
baseURL = "https://gjolleyrogers.github.io"
languageCode = "en-us"
theme = ["ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 12 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Electrify Canberra"
    weight = 1
    contentDir = "content"
    # languageDirection = 'rtl' for Right-To-Left languages
 
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


[params]
  text_color = ""
  author = "GJR"
  favicon = "/images/logo.png" 
   date_format = "2. January 2006"
  description = "  Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 5
  show_reading_time=true
  toc=true
  #comments?
# disqusShortname = "YOURSHORTNAME"
# commentoEnable = true
 
 

[taxonomies]
  category = 'categories'
  tag = 'tags'
  
[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"

[[params.ananke_socials]]
 name = "facebook"
 url = "https://facebook.com/"  
 
 [[params.ananke_socials]]
 name = "rss" 